services:
  # Let's create our background worker
  - type: worker
    name: sidekiq-worker
    env: ruby
    region: oregon
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: wynterai
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
